name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AIRFLOWSERVER }}
        username: ${{ secrets.AIRFLOWUSER }}
        password: ${{ secrets.AIRFLOWPASSWORD }}
        port: ${{ secrets.AIRFLOWPORT }}
        source: "dags/*.py"
        target: "/opt/airflow/dags/"
        overwrite: true
